#pragma once

#define MAX_ROOM_PLAYER (8)
#define MAX_BUF_SIZE (1300)
#define MAX_PACKET_SIZE (1300)
#define MAX_USER (5000)
#define SERVER_PORT (51341)
#define MAX_USER_NAME_LENGTH (11)
#define MAX_USING_ITEM (6)
#define MAX_UN_USING_ITEM (8)
#define BATTLE_ITEM_QUEUE_LOOP_COUNT (5)
#define CHOOSE_CHARACTER_TIME (60)
#define BATTLE_READY_TIME (60)
constexpr int BATTLE_ITEM_QUEUE_LENGTH = MAX_ROOM_PLAYER * MAX_USING_ITEM * BATTLE_ITEM_QUEUE_LOOP_COUNT * 2 + MAX_ROOM_PLAYER;
constexpr int MAX_ROOM_COUNT = MAX_USER / MAX_ROOM_PLAYER;